apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example-pod
spec:
  containers:
  - name: example-pod
    image: nginx:1.14.2		# 사용할 이미지
    ports:
    - containerPort: 80
    livenessProbe:		# 컨테이너 생성후 정상적으로 동작하는지 체크. 실패하는 경우 컨테이너 재시작
      httpGet:			# GET method를 이용해서 컨테이터 동작 체크
        path: /
        port: 80
      initialDelaySeconds: 5	# 초기 실행 딜레이
      timeoutSeconds: 3		# timeout. 기본값은 1초
      periodSeconds: 5		# 재시도 주기 시간. 기본값은 10초
      failureThreshold: 2	# 실패로 간주되는 최대 시간. 기본값은 3초
    readinessProbe:		# 컨테이너가 준비되었는지 체크. 실패하는 경우 Pod에서 제외.
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 2
