apiVersion: v1
kind: Service
metadata:
  name: example-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: example-pod
    tier: app
  ports:
    - port: 30000
      protocol: TCP
      targetPort: 80
